name: 'OpenVPN Connect Windows'
description: 'Establish OpenVPN connection on Windows runners'
author: 'jworford'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  config:
    description: 'OpenVPN configuration file content (.ovpn)'
    required: true
  username:
    description: 'OpenVPN username'
    required: true
  password:
    description: 'OpenVPN password'
    required: true
  test-connection:
    description: 'Test connection to specific host:port (format: host:port)'
    required: false
    default: ''
  connection-timeout:
    description: 'Timeout in seconds to wait for VPN connection'
    required: false
    default: '45'
  max-test-attempts:
    description: 'Maximum connection test attempts'
    required: false
    default: '10'

runs:
  using: 'composite'
  steps:
    - name: Setup OpenVPN Connection
      run: |
        $ErrorActionPreference = "Stop"
        
        Write-Host "Setting up OpenVPN connection..."
        
        # Create OpenVPN config file from input
        echo '${{ inputs.config }}' | Out-File -FilePath "client.ovpn" -Encoding UTF8
        Write-Host "OpenVPN config file created"
        
        # Install OpenVPN using Chocolatey
        Write-Host "Installing OpenVPN using Chocolatey..."
        $chocoResult = Start-Process choco -ArgumentList "install", "openvpn", "-y", "--no-progress" -Wait -PassThru -NoNewWindow
        Write-Host "Chocolatey installation exit code: $($chocoResult.ExitCode)"
        
        if ($chocoResult.ExitCode -ne 0) {
          Write-Host "ERROR: Chocolatey installation failed"
          exit 1
        }
        
        Write-Host "OpenVPN installed successfully"
        
        # Verify OpenVPN installation
        $openvpnPath = "C:\Program Files\OpenVPN\bin\openvpn.exe"
        if (-not (Test-Path $openvpnPath)) {
          Write-Host "ERROR: OpenVPN executable not found at expected location"
          exit 1
        }
        
        Write-Host "Found OpenVPN at: $openvpnPath"
        
        # Create auth file with username and password
        $auth = @"
        ${{ inputs.username }}
        ${{ inputs.password }}
        "@
        $auth | Out-File -FilePath "auth.txt" -Encoding UTF8

        Write-Host "Authentication file created"
        
        # Start OpenVPN connection
        Write-Host "Starting OpenVPN connection using: $openvpnPath"
        $process = Start-Process -FilePath $openvpnPath -ArgumentList "--config", "client.ovpn", "--auth-user-pass", "auth.txt", "--log", "openvpn.log" -PassThru -NoNewWindow
        
        # Wait for connection to establish
        Start-Sleep -Seconds 45
        
        # Check if process is still running
        if ($process -and !$process.HasExited) {
          Write-Host "OpenVPN process is running"
        } else {
          Write-Host "ERROR: OpenVPN process failed to start or exited unexpectedly"
          exit 1
        }
        
        Write-Host "OpenVPN connection setup complete"
      shell: powershell