name: 'OpenVPN Connect Windows'
description: 'Establish OpenVPN connection on Windows runners'
author: 'jworford'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  config:
    description: 'OpenVPN configuration file content (.ovpn)'
    required: true
  username:
    description: 'OpenVPN username'
    required: true
  password:
    description: 'OpenVPN password'
    required: true
  test-connection:
    description: 'Test connection to specific host:port (format: host:port)'
    required: false
    default: ''
  connection-timeout:
    description: 'Timeout in seconds to wait for VPN connection'
    required: false
    default: '45'
  max-test-attempts:
    description: 'Maximum connection test attempts'
    required: false
    default: '10'

runs:
  using: 'composite'
  steps:
    - name: Setup OpenVPN Connection
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"
        
        Write-Host "🔧 Setting up OpenVPN connection..."
        
        # Create OpenVPN config file from input
        '${{ inputs.config }}' | Out-File -FilePath "client.ovpn" -Encoding UTF8
        Write-Host "✓ OpenVPN config file created"
        
        # Install OpenVPN using Chocolatey
        Write-Host "📦 Installing OpenVPN using Chocolatey..."
        $chocoResult = Start-Process choco -ArgumentList "install", "openvpn", "-y", "--no-progress" -Wait -PassThru -NoNewWindow
        
        if ($chocoResult.ExitCode -ne 0) {
          Write-Host "❌ ERROR: Chocolatey installation failed"
          exit 1
        }
        
        Write-Host "✓ OpenVPN installed successfully"
        
        # Verify OpenVPN installation
        $openvpnPath = "C:\Program Files\OpenVPN\bin\openvpn.exe"
        if (-not (Test-Path $openvpnPath)) {
          Write-Host "❌ ERROR: OpenVPN executable not found at expected location"
          exit 1
        }
        
        # Create auth file with username and password
        $username = '${{ inputs.username }}'
        $password = '${{ inputs.password }}'
        $authContent = "$username`n$password"
        $authContent | Out-File -FilePath "auth.txt" -Encoding UTF8
        Write-Host "✓ Authentication file created"
        
        # Start OpenVPN connection
        Write-Host "🚀 Starting OpenVPN connection..."
        $process = Start-Process -FilePath $openvpnPath -ArgumentList "--config", "client.ovpn", "--auth-user-pass", "auth.txt", "--log", "openvpn.log" -PassThru -NoNewWindow
        
        # Store process ID for cleanup
        $processId = $process.Id
        Write-Host "📋 OpenVPN process ID: $processId"
        
        # Store process ID in environment variable for cleanup
        echo "OPENVPN_PROCESS_ID=$processId" >> $env:GITHUB_ENV
        
        # Wait for connection to establish
        $timeout = [int]'${{ inputs.connection-timeout }}'
        Write-Host "⏳ Waiting $timeout seconds for VPN connection to establish..."
        Start-Sleep -Seconds $timeout
        
        # Verify process is running
        if (-not $process -or $process.HasExited) {
          Write-Host "❌ ERROR: OpenVPN process failed to start or exited unexpectedly"
          exit 1
        }
        
        Write-Host "✓ OpenVPN process is running (PID: $processId)"
        
        # Test connection if specified
        $testConnection = '${{ inputs.test-connection }}'
        if ($testConnection -and $testConnection -ne '') {
          Write-Host "🔍 Testing connection to $testConnection..."
          $parts = $testConnection.Split(':')
          if ($parts.Length -eq 2) {
            $testHost = $parts[0]
            $testPort = [int]$parts[1]
            $maxAttempts = [int]'${{ inputs.max-test-attempts }}'
            $connected = $false
            
            for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
              Write-Host "Connection test attempt $attempt of $maxAttempts..."
              
              try {
                $result = Test-NetConnection -ComputerName $testHost -Port $testPort -InformationLevel Quiet -WarningAction SilentlyContinue
                if ($result) {
                  Write-Host "✅ VPN connection established successfully - target server is reachable"
                  $connected = $true
                  break
                }
              } catch {
                Write-Host "⚠️ Connection test failed: $($_.Exception.Message)"
              }
              
              if ($attempt -lt $maxAttempts) {
                Start-Sleep -Seconds 5
              }
            }
            
            if (-not $connected) {
              Write-Host "❌ ERROR: Failed to establish connection to $testHost`:$testPort after $maxAttempts attempts"
              exit 1
            }
          } else {
            Write-Host "⚠️ WARNING: Invalid test-connection format. Use 'host:port'"
          }
        }
        
        Write-Host "🎉 OpenVPN connection setup complete"
        
    - name: Cleanup OpenVPN (Always runs)
      shell: powershell
      if: always()
      run: |
        $ErrorActionPreference = "Continue"
        
        Write-Host "🧹 Starting OpenVPN cleanup..."
        
        # Try to get process ID from environment
        $processId = $env:OPENVPN_PROCESS_ID
        
        if ($processId) {
          Write-Host "🔍 Found stored OpenVPN process ID: $processId"
          
          try {
            # Check if process is still running
            $process = Get-Process -Id $processId -ErrorAction SilentlyContinue
            
            if ($process) {
              Write-Host "🛑 Terminating OpenVPN process (PID: $processId)..."
              Stop-Process -Id $processId -Force
              
              # Wait a moment and verify termination
              Start-Sleep -Seconds 2
              $process = Get-Process -Id $processId -ErrorAction SilentlyContinue
              
              if (-not $process) {
                Write-Host "✅ OpenVPN process terminated successfully"
              } else {
                Write-Host "⚠️ OpenVPN process may still be running"
              }
            } else {
              Write-Host "ℹ️ OpenVPN process already terminated"
            }
          } catch {
            Write-Host "⚠️ Error during process termination: $($_.Exception.Message)"
          }
        } else {
          Write-Host "⚠️ No stored process ID found, attempting to find OpenVPN processes..."
          
          # Fallback: Find and terminate any OpenVPN processes
          try {
            $openvpnProcesses = Get-Process -Name "openvpn" -ErrorAction SilentlyContinue
            
            if ($openvpnProcesses) {
              Write-Host "🔍 Found $($openvpnProcesses.Count) OpenVPN process(es)"
              
              foreach ($proc in $openvpnProcesses) {
                Write-Host "🛑 Terminating OpenVPN process (PID: $($proc.Id))..."
                try {
                  Stop-Process -Id $proc.Id -Force
                  Write-Host "✅ Process $($proc.Id) terminated"
                } catch {
                  Write-Host "⚠️ Failed to terminate process $($proc.Id): $($_.Exception.Message)"
                }
              }
            } else {
              Write-Host "ℹ️ No OpenVPN processes found"
            }
          } catch {
            Write-Host "⚠️ Error finding OpenVPN processes: $($_.Exception.Message)"
          }
        }
        
        # Clean up temporary files
        Write-Host "🗑️ Cleaning up temporary files..."
        
        $filesToClean = @("client.ovpn", "auth.txt", "openvpn.log")
        foreach ($file in $filesToClean) {
          if (Test-Path $file) {
            try {
              Remove-Item $file -Force
              Write-Host "✅ Removed $file"
            } catch {
              Write-Host "⚠️ Failed to remove $file`: $($_.Exception.Message)"
            }
          }
        }
        
        Write-Host "🎉 OpenVPN cleanup complete"
