name: 'OpenVPN Connect Windows'
description: 'Establish OpenVPN connection on Windows runners'
author: 'jworford'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  config:
    description: 'OpenVPN configuration file content (.ovpn)'
    required: true
  username:
    description: 'OpenVPN username'
    required: true
  password:
    description: 'OpenVPN password'
    required: true
  test-connection:
    description: 'Test connection to specific host:port (format: host:port)'
    required: false
    default: ''
  connection-timeout:
    description: 'Timeout in seconds to wait for VPN connection'
    required: false
    default: '45'
  max-test-attempts:
    description: 'Maximum connection test attempts'
    required: false
    default: '10'

runs:
  using: 'composite'
  steps:
    - name: Setup OpenVPN Connection
      shell: powershell
      run: |
        $ErrorActionPreference = "Stop"
        
        Write-Host "Setting up OpenVPN connection..."
        
        # Create OpenVPN config file from input
        '${{ inputs.config }}' | Out-File -FilePath "client.ovpn" -Encoding UTF8
        Write-Host "OpenVPN config file created"
        
        # Install OpenVPN using Chocolatey
        Write-Host "Installing OpenVPN using Chocolatey..."
        $chocoResult = Start-Process choco -ArgumentList "install", "openvpn", "-y", "--no-progress" -Wait -PassThru -NoNewWindow
        
        if ($chocoResult.ExitCode -ne 0) {
          Write-Host "ERROR: Chocolatey installation failed"
          exit 1
        }
        
        Write-Host "OpenVPN installed successfully"
        
        # Verify OpenVPN installation
        $openvpnPath = "C:\Program Files\OpenVPN\bin\openvpn.exe"
        if (-not (Test-Path $openvpnPath)) {
          Write-Host "ERROR: OpenVPN executable not found at expected location"
          exit 1
        }
        
        # Create auth file with username and password
        $auth = @"
        ${{ inputs.username }}
        ${{ inputs.password }}
        "@
        $auth | Out-File -FilePath "auth.txt" -Encoding UTF8
        Write-Host "Authentication file created"
        
        # Setup OpenVPN service directories
        $configDir = "C:\Program Files\OpenVPN\config"
        $logDir = "C:\Program Files\OpenVPN\log"
        
        # Create directories if they don't exist
        if (-not (Test-Path $configDir)) {
          New-Item -ItemType Directory -Path $configDir -Force
        }
        if (-not (Test-Path $logDir)) {
          New-Item -ItemType Directory -Path $logDir -Force
        }
        
        # Copy config and auth files to OpenVPN config directory
        Copy-Item "client.ovpn" -Destination "$configDir\client.ovpn" -Force
        Copy-Item "auth.txt" -Destination "$configDir\auth.txt" -Force
        
        Write-Host "Config files copied to OpenVPN directory"
        
        # Install and start OpenVPN service
        Write-Host "Setting up OpenVPN service..."
        
        # Check for OpenVPN service executable
        $serviceExePaths = @(
          "C:\Program Files\OpenVPN\bin\openvpnserv2.exe",
          "C:\Program Files\OpenVPN\bin\openvpnserv.exe",
          "C:\Program Files (x86)\OpenVPN\bin\openvpnserv2.exe",
          "C:\Program Files (x86)\OpenVPN\bin\openvpnserv.exe"
        )
        
        $serviceExe = $null
        foreach ($path in $serviceExePaths) {
          if (Test-Path $path) {
            $serviceExe = $path
            Write-Host "Found OpenVPN service executable: $serviceExe"
            break
          }
        }
        
        if ($serviceExe) {
          Write-Host "Installing OpenVPN service..."
          
          # Check if service already exists
          $existingService = Get-Service -Name "OpenVPN" -ErrorAction SilentlyContinue
          if ($existingService) {
            Write-Host "OpenVPN service already exists, skipping installation"
          } else {
            $serviceResult = Start-Process -FilePath $serviceExe -ArgumentList "-install" -Wait -PassThru -NoNewWindow
            
            if ($serviceResult.ExitCode -ne 0) {
              Write-Host "WARNING: Service install returned exit code: $($serviceResult.ExitCode)"
              Write-Host "This may be normal if the service already exists"
            } else {
              Write-Host "OpenVPN service installed successfully"
            }
          }
        } else {
          Write-Host "WARNING: OpenVPN service executable not found. Attempting to start service anyway..."
        }
        
        # Start the OpenVPN service
        Write-Host "Starting OpenVPN service..."
        Start-Service -Name "OpenVPN" -ErrorAction SilentlyContinue
        
        # Wait a moment for service to initialize
        Start-Sleep -Seconds 10
        
        # Check service status
        $service = Get-Service -Name "OpenVPN" -ErrorAction SilentlyContinue
        if ($service -and $service.Status -eq "Running") {
          Write-Host "OpenVPN service started successfully"
        } else {
          Write-Host "WARNING: OpenVPN service may not be running properly"
          if ($service) {
            Write-Host "Service status: $($service.Status)"
          } else {
            Write-Host "Service not found"
          }
        }
        
        # Define log file paths - try multiple possible locations
        $logPaths = @(
          "$logDir\client.log",
          "$logDir\openvpn.log", 
          "C:\Program Files\OpenVPN\log\client.log",
          "C:\Program Files\OpenVPN\log\openvpn.log"
        )
        
        $log = $null
        foreach ($logPath in $logPaths) {
          if (Test-Path $logPath) {
            $log = $logPath
            Write-Host "Found log file at: $log"
            break
          }
        }
        
        if (-not $log) {
          # Default to expected location even if it doesn't exist yet
          $log = "$logDir\client.log"
          Write-Host "Using default log path: $log"
        }
        
        # Wait for connection to establish
        $timeout = [int]'${{ inputs.connection-timeout }}'
        Write-Host "Waiting for VPN connection to establish..."
        $up = $false
        $attempts = 0
        $maxAttempts = [int]'${{ inputs.max-test-attempts }}'
        
        while ($attempts -lt $maxAttempts -and -not $up) {
          Start-Sleep -Seconds 5
          $attempts++
          
          Write-Host "Connection attempt $attempts of $maxAttempts..."
          
          # Check if log file exists and has connection success
          if (Test-Path $log) {
            if (Select-String -Path $log -Pattern "Initialization Sequence Completed" -ErrorAction SilentlyContinue) {
              $up = $true
              Write-Host "Found 'Initialization Sequence Completed' in log"
              break
            }
          }
          
          # Also check for any OpenVPN processes as fallback
          $openvpnProcs = Get-Process -Name "openvpn" -ErrorAction SilentlyContinue
          if ($openvpnProcs) {
            Write-Host "OpenVPN process detected (PID: $($openvpnProcs[0].Id))"
            
            # If we have a process running for more than 30 seconds, assume connection is up
            if ($attempts -ge 6) {
              Write-Host "OpenVPN process has been running for sufficient time, assuming connection is established"
              $up = $true
              break
            }
          }
          
          # Check service status
          $currentService = Get-Service -Name "OpenVPN" -ErrorAction SilentlyContinue
          if ($currentService) {
            Write-Host "Service status: $($currentService.Status)"
          }
        }

        if (-not $up) {
          Write-Host "ERROR: Tunnel never initialized after $maxAttempts attempts. Checking logs..."
          if (Test-Path $log) {
            Write-Host "=== Last lines of $log ==="
            Get-Content $log -Tail 50 -ErrorAction SilentlyContinue
          } else {
            Write-Host "Log file not found at: $log"
          }
          
          # Check service status
          $service = Get-Service -Name "OpenVPN" -ErrorAction SilentlyContinue
          if ($service) {
            Write-Host "OpenVPN service status: $($service.Status)"
          }
          
          exit 1
        }
        
        Write-Host "VPN connection established successfully"
        
        # Test connection if specified
        $testConnection = '${{ inputs.test-connection }}'
        if ($testConnection) {
          $parts = $testConnection.Split(':')
          if ($parts.Length -eq 2) {
            $testHost = $parts[0]
            $testPort = [int]$parts[1]
            
            Write-Host "Testing connection to $testHost`:$testPort..."
            $maxAttempts = [int]'${{ inputs.max-test-attempts }}'
            $connected = $false
            
            for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
              Write-Host "Connection test attempt $attempt of $maxAttempts..."
              
              $result = Test-NetConnection -ComputerName $testHost -Port $testPort -InformationLevel Quiet -WarningAction SilentlyContinue
              if ($result) {
                Write-Host "VPN connection established successfully - target server is reachable"
                $connected = $true
                break
              }
              
              if ($attempt -lt $maxAttempts) {
                Start-Sleep -Seconds 5
              }
            }
            
            if (-not $connected) {
              Write-Host "ERROR: Failed to establish connection to $testHost`:$testPort after $maxAttempts attempts"
              exit 1
            }
          } else {
            Write-Host "WARNING: Invalid test-connection format. Use 'host:port'"
          }
        }
        
        Write-Host "OpenVPN connection setup complete"
        
    - name: Cleanup OpenVPN (Always runs)
      shell: powershell
      if: always()
      run: |
        $ErrorActionPreference = "Continue"
        
        Write-Host "Starting OpenVPN cleanup..."
        
        # Try to get process ID from environment
        $processId = $env:OPENVPN_PROCESS_ID
        
        if ($processId) {
          Write-Host "Found stored OpenVPN process ID: $processId"
          
          try {
            # Check if process is still running
            $process = Get-Process -Id $processId -ErrorAction SilentlyContinue
            
            if ($process) {
              Write-Host "Terminating OpenVPN process (PID: $processId)..."
              Stop-Process -Id $processId -Force
              
              # Wait a moment and verify termination
              Start-Sleep -Seconds 2
              $process = Get-Process -Id $processId -ErrorAction SilentlyContinue
              
              if (-not $process) {
                Write-Host "OpenVPN process terminated successfully"
              } else {
                Write-Host "OpenVPN process may still be running"
              }
            } else {
              Write-Host "OpenVPN process already terminated"
            }
          } catch {
            Write-Host "Error during process termination: $($_.Exception.Message)"
          }
        } else {
          Write-Host "No stored process ID found, attempting to find OpenVPN processes..."
          
          # Fallback: Find and terminate any OpenVPN processes
          $openvpnProcesses = Get-Process -Name "openvpn" -ErrorAction SilentlyContinue
          
          if ($openvpnProcesses) {
            Write-Host "Found $($openvpnProcesses.Count) OpenVPN process(es)"
            
            foreach ($proc in $openvpnProcesses) {
              Write-Host "Terminating OpenVPN process (PID: $($proc.Id))..."
              try {
                Stop-Process -Id $proc.Id -Force
                Write-Host "Process $($proc.Id) terminated"
              } catch {
                Write-Host "Failed to terminate process $($proc.Id): $($_.Exception.Message)"
              }
            }
          } else {
            Write-Host "No OpenVPN processes found"
          }
        }
        
        # Clean up temporary files
        Write-Host "Cleaning up temporary files..."
        
        $filesToClean = @("client.ovpn", "auth.txt", "openvpn.log")
        foreach ($file in $filesToClean) {
          if (Test-Path $file) {
            try {
              Remove-Item $file -Force
              Write-Host "Removed $file"
            } catch {
              Write-Host "Failed to remove $file`: $($_.Exception.Message)"
            }
          }
        }
        
        Write-Host "OpenVPN cleanup complete"